### ISSUE TITLE
When you click services in the menu

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#10]
Can it take you to this section of the homepage?

<img width="1271" alt="Screen Shot 2019-11-28 at 1 35 40 pm" src="https://user-images.githubusercontent.com/55725505/69772433-0b6b0480-11e4-11ea-991c-0c36ef55df68.png">

**Comment by markendley** [comment]
It does.

The link is http://marke2.sg-host.com/emilygardem/#services

That means it'll take you to the homepage and then scroll you down to the services section

**Comment by markendley** [comment]
What happens when you click on it?

**Comment by LaraStudioFriday** [comment]
Oh I mean it takes you this "SECTION" on the homepage - not just the homepage banner image.
