### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#11]
Under Emily's image can we please include this text:

emily.gardem.nutrition@gmail.com 

0459 775 231 

I currently offer consultations through my private practice in Shellharbour, with Skype/Online/Phone and in home visits also being available.  

I am available: 

Monday, Tuesdays, Thursdays 9:30am – 4:00pm 

Saturdays 9:00am – 4:00pm 

Alternative appointment’s available on request

**Comment by markendley** [comment]
This kinda goes against the template, so just small and centered, ... just make it look nice?

$20 +GST

**Comment by markendley** [comment]
Oh, I gotta make a new field... $30 +GST
