### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#12]
Just as Butler has this - https://butlerhr.com.au/privacy-policy-butler-hr/

Can we link into the footer of the website Terms & Conditions (here this text will sit)

Mobile Consultations 

I offer mobile consultations, meaning I can come to you.  

Travel within a 10km radius of Shellharbour City, does not incur a travel charge. Travel in a 10 – 15km radius and extra $10 will be added to the final cost. For 15 – 20km an extra $15 will be added. For an extra 25km, and extra $25 will be added. Travel of up to an hour each way can be arranged at the rate of $30/hr.  

Payment 

Payment can be either upon booking or at the start of face to face/phone/online consultations. I accept bank transfer, debit/credit card or cash. 

Health fund rebates 

I am an accredited member of the Australian Natural Therapists Association (ANTA), and the Nutrition Society of Australia (NSA), enabling clients to claim rebates from many private health care providers, depending on the level of extras cover. Please check eligibility with your fund.  

 You will be issued with a receipt after your consultation, which you can submit to your private health fund. Please be aware that Health fund rebates are NOT available for Skype consultations. 

Cancellation Policy (Consultations) 

Please be aware that there is a 24-hour cancellation policy. Emily understands that your time is important and circumstances can change, and appreciates that you understand her time is valuable too. Any cancellations that occur 24 hours or more before the scheduled appointment, are able to be rebooked at no extra cost. However, if you wish to cancel or reschedule your appointment, and 24 hours notice is not given, or you do not show up for your appointment, a 50% cancellation fee does apply. A reminder will be sent to you the week of your appointment.

**Comment by markendley** [comment]
I'll need to adjust the layout of the footer to fit the new T&C link.
I'll also need to code a new page style.
$30 +GST

**Comment by LaraStudioFriday** [comment]
ok, please proceed

**Comment by markendley** [comment]
done

**Comment by markendley** [comment]
http://marke2.sg-host.com/emilygardem/terms-conditions/

though we still need the footer redesigend

**Comment by LaraStudioFriday** [comment]
This is a low budget site - so any quick and easy fix you can think of?

**Comment by markendley** [comment]
ok, I just added a black bar at the bottom

**Comment by LaraStudioFriday** [comment]
Cool - im thinking the ANTA logo will look ugly in the footer - and will talk to Emily
