### ISSUE TITLE
Need to add this logo to the footer of the website

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#14]
![ANTA-Logo-JPG-280x280](https://user-images.githubusercontent.com/55725505/69774025-bf6e8e80-11e8-11ea-9cac-b59bdcfed232.jpg)

**Comment by markendley** [comment]
hmm....

If it were me, I'll put "©2019 Emily Gardem All rights reserved" onto it's own line (own bar) (maybe make the bar pitch black). Then I'll add this logo next to the social media icons.

How small can I make this logo?

If you like that idea $70 +GST

**Comment by LaraStudioFriday** [comment]
This sounds a bit expensive to add a logo. 

Is there a way to put it in and add the text Terms and Conditions but not adding too much extra cost

**Comment by markendley** [comment]
It may look like just a simple footer but if you look closely it's built out of multiple parts (the logo on the side, the social media anchored to the right...) 

Chucking in the logo and T&C link might seem simple for a large desktop but then I gotta rearrange it for tablet and mobile.

**Comment by markendley** [comment]
What I can do for free is simply add another bar at the very bottom (make it pitche black) and then place the logo and T&C in there.

Question is how small can this logo be?
And have you got a transparent version?

**Comment by LaraStudioFriday** [comment]
Just pop in the footer next to the T&C's. thanks. have emailed you the logo

**Comment by markendley** [comment]
done
