### ISSUE TITLE
Images on a phone

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#15]
On homepage and about page, they look very odd
![77247456_470626193805562_5503328075254857728_n](https://user-images.githubusercontent.com/55725505/69834563-46764200-128f-11ea-9278-bcd24df1d94f.jpg)
![77368867_883774902042321_3519906822137839616_n](https://user-images.githubusercontent.com/55725505/69834584-6279e380-128f-11ea-80cb-1b951385d49f.jpg)

**Comment by markendley** [comment]
fixed

**Comment by LaraStudioFriday** [comment]
they still looks really squashed on my phone - viewed in private window
