### ISSUE TITLE
Please remove the squiggly line from the site

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#16]
e.g 
<img width="263" alt="Screen Shot 2019-12-03 at 9 51 01 am" src="https://user-images.githubusercontent.com/55725505/70001842-76d11f80-15b2-11ea-8234-81f9b2d460e0.png">
![Uploading Screen Shot 2019-12-03 at 9.51.08 am.png…]()

**Comment by markendley** [comment]
done
