### ISSUE TITLE
Cluncky

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#17]
We are finding this site a bit clunky to use - there is not much that emily will be able to add later on. 

We would like to add a sub menu to Packages - for the 3 packages but are unable to do this.

**Comment by markendley** [comment]
Sorry, but you've gotta expect these kinds of things when we build over another site.

If you want me to be flexible with budget you gotta be flexible as well.

There was no dropdown in the designs, but I just turned it back on.
