### ISSUE TITLE
Service page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#18]
Would like a service 'page' that when a user clicks on it it takes them straight to the services - instead of going to the homepage. 

ALSO, this page needs to incorporate this text:

Fees & Services 

Fees 

Standard Consultations: face to face and Skype/phone/online 

90 Minute Initial Consultation $130 

60 minute follow up consultation $ 90 

Concession rates are available, please ask Emily upon enquiry. 

What does a consultation involve? 

An Initial consultation involves building a detailed picture of your diet and lifestyle, which takes into consideration your full health history, current health issues, a complete dietary analysis, assessment of physical activity and current lifestyle, and of course your goals and priorities. 

Following this, I will develop a treatment plan based on your individual needs. In addition, sessions may include referral for diagnostics/pathology testing, nutritional supplementation, the use of dietary analysis software and Bio Impedance Analysis (BIA is excluded from Skype consultations) in order for me to provide a thorough review of diet and body composition and better track health and nutrition goals.  

Follow-up consultations are 60 minutes in duration, discuss your progress, any concerns or new issues that may have arisen and adjust treatment plan as required. I recommend that you follow up with at least one nutrition consultation in order for me to review your progress, however I will outline a detailed schedule of appointments recommended to you based on your individual needs.

One idea is to have the yellow coloured bar (keeping in enquiry and call buttons) 

<img width="1278" alt="Screen Shot 2019-12-03 at 1 37 26 pm" src="https://user-images.githubusercontent.com/55725505/70015643-1ce05200-15d2-11ea-8b90-24396b9e218c.png">
- for this text:
Fees & Services 

Fees 

Standard Consultations: face to face and Skype/phone/online 

90 Minute Initial Consultation $130 

60 minute follow up consultation $ 90 

Concession rates are available, please ask Emily upon enquiry. 

Then introduce that purple bar below for the rest of the text. 

<img width="1275" alt="Screen Shot 2019-11-28 at 1 26 20 pm" src="https://user-images.githubusercontent.com/55725505/70015693-3a152080-15d2-11ea-96ca-a77a07fa351f.png">

Without the enquiry and call buttons

**Comment by markendley** [comment]
I can make something re-using the  http://marke2.sg-host.com/emilygardem/about/ template?

I'll just use place holder images and then when I'm done you can change the images later?

$90+GST

**Comment by LaraStudioFriday** [comment]
Ok, instead of having packages, please ca we have the services instead listed. 

<img width="1275" alt="Screen Shot 2019-12-03 at 2 44 44 pm 1" src="https://user-images.githubusercontent.com/55725505/70018884-9597dc00-15db-11ea-867e-f88bf758a9ea.png">

<img width="1273" alt="Screen Shot 2019-12-03 at 2 46 03 pm" src="https://user-images.githubusercontent.com/55725505/70018916-a9dbd900-15db-11ea-9942-78299fa5e5c6.png">

**Comment by markendley** [comment]
So make something out of the About us template, but instead of having the packages section we have that services section?

**Comment by LaraStudioFriday** [comment]
Sending you a video

**Comment by markendley** [comment]
ok got it

check it out
http://marke2.sg-host.com/emilygardem/our-services/
