### ISSUE TITLE
Homepage text

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#2]
Ho can I update this text?

<img width="876" alt="Screen Shot 2019-11-28 at 1 24 04 pm" src="https://user-images.githubusercontent.com/55725505/69771874-67348e00-11e2-11ea-933c-5c7487eeb463.png">

**Comment by markendley** [comment]
You gotta go to Pages
Then into the Homepage
Then you'll see the Slider fields at the bottom

http://marke2.sg-host.com/emilygardem/wp-admin/post.php?post=448&action=edit
