### ISSUE TITLE
Consistent images

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#20]
Can all these circle images be consistent across all - on all pages?

<img width="583" alt="Screen Shot 2019-12-03 at 2 29 15 pm" src="https://user-images.githubusercontent.com/55725505/70018157-5bc5d600-15d9-11ea-9f7a-aeef16487bd6.png">

![79141153_3106062152772507_7258898676209156096_n](https://user-images.githubusercontent.com/55725505/70018190-78620e00-15d9-11ea-8266-32170c8b2d2a.jpg)

**Comment by markendley** [comment]
You mean the same size throughout?

$30
