### ISSUE TITLE
Instagram feed

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#21]
The client would like to know if if its not too late - is it possible to have a gallery on my website which Is fed from instagram, tile style?

**Comment by markendley** [comment]
For free I can just add it to the footer?

**Comment by LaraStudioFriday** [comment]
Will you see any images?? can you show me an example?

**Comment by markendley** [comment]
OK, here's one I did (at the bottom)
https://www.burgerproject.com/

so for Emily, I can just have ONE row

**Comment by LaraStudioFriday** [comment]
Those burgers are making me hungry!! 

Yeah go for it, thanks

**Comment by markendley** [comment]
hehe

Well it's all ready, she just needs to go to this page and then click the big blue Instagram button, so then it'll sync to her Instagram account instead of mine.

http://marke2.sg-host.com/emilygardem/wp-admin/admin.php?page=sb-instagram-feed&tab=configure

**Comment by markendley** [comment]
![Screen Shot 2019-12-04 at 11 47 25 am](https://user-images.githubusercontent.com/6570606/70102353-e8c96780-168b-11ea-823f-2c0148765a37.png)

**Comment by LaraStudioFriday** [comment]
How many images will appear on 1 row?

**Comment by markendley** [comment]
6

**Comment by markendley** [comment]
or I can change it to 7 or 5?

**Comment by LaraStudioFriday** [comment]
6 is cool

**Comment by markendley** [comment]
ok it's all ready then

**Comment by LaraStudioFriday** [comment]
Sorry - is there any chance we can give the insta a title? Like you did with the burgers?

Follow me

Just to give it some space, and not look like random images at the bottom of the page?

**Comment by markendley** [comment]
the title and follow me button I coded that myself, but this plugin comes with it's own that I just turned on.
