### ISSUE TITLE
When you click Packages in the menu

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/emlygrdm#8]
can it take you to this section of the homepage?
<img width="1261" alt="Screen Shot 2019-11-28 at 1 32 51 pm" src="https://user-images.githubusercontent.com/55725505/69772303-a6afaa00-11e3-11ea-84c4-9369f449132e.png">

**Comment by markendley** [comment]
Yes it does.

What happens when you click on it?

**Comment by LaraStudioFriday** [comment]
<img width="1280" alt="Screen Shot 2019-12-02 at 1 31 56 pm" src="https://user-images.githubusercontent.com/55725505/69926324-2604ec80-1508-11ea-879d-4398771d86b6.png">
